### PR TITLE
blinkR30 examples for PRU BBAI

### PR DESCRIPTION
**Pull request by lorforlinux**
@jadonk @MarkAYoder please review my code :)

### CODE REVIEW

**Comment by MarkAYoder** [comment]
@lorforlinux it looks good.  I'll fire up my AI in a day or so and check it out.

**Comment by lorforlinux** [comment]
@MarkAYoder Okay, thanks :)

**Comment by MarkAYoder** [comment]
@lorforlinux I'm working on running your examples on the AI.  They are compiling fine.
I've gotten the overlays compiled for the config--pin.
How do you load the overlays?

**Comment by lorforlinux** [comment]
@MarkAYoder Hi, please add this to `/boot/uEnv.txt` of BBAI

```
enable_uboot_overlays=1
uboot_overlay_addr0=BBAI-PRUOUT_PRU1_0.dtbo
uboot_overlay_addr1=BBAI-PRUOUT_PRU1_1.dtbo
uboot_overlay_addr2=BBAI-PRUOUT_PRU2_0.dtbo
uboot_overlay_addr3=BBAI-PRUOUT_PRU2_1.dtbo
```

**Comment by MarkAYoder** [comment]
Thanks, I had forgotten the `enable_uboot_overlays=1`.

All four blink examples work!

Could you add in the comments in each .c file more details about editing /boot/uEnv.txt?

**Comment by lorforlinux** [comment]
Sure, I will add the comments ASAP ;)

**Comment by lorforlinux** [comment]
@MarkAYoder I have updated the files, please merge the changes if everything is up to your mark.

**Comment by lorforlinux** [comment]
@jadonk can you merge this, please?

**Comment by jadonk** [comment]
Please change the pull request to v2020.08, not v2020.01.

**Pull request closed without merging**
